112 create component students list reusable student list item
boolean-uk/team-dev-frontend-client pull request #143
Opened 2022-11-28 14:07 UTC by OlhaDorofiychuk

students list and students list item components created

2022-11-28 14:28 UTC, Auenc requested changes

2022-11-28 14:28 UTC, Auenc commented on src/components/Cohorts/StudentList/StudentsList.js
> +  const [students, setStudents] = useState([])
It doesn't look like this state is used, can we remove it?

2022-11-28 14:28 UTC, Auenc commented on src/components/Cohorts/StudentList/StudentsList.js
> +      setStudents(studentsOnly)
If we don't need the student state, we can remove this. 

If it is needed, we might need to refactor this as I suspect there might be a bug when trying to update two states in the same `.then`

2022-11-28 14:28 UTC, Auenc commented on src/components/Cohorts/StudentList/StudentsList.js
> +        <u>{cohort.startDate}</u> -<u>{cohort.endDate}</u>
I don't `startDate` and `endDate` should be in a`p` tag as it's not a paragraph

2022-11-28 14:28 UTC, Auenc commented on src/components/Cohorts/StudentList/StudentsList.js
> +      {renderInfo === false
Let's refactor this, nested ternary statements are very hard to read.

2022-11-28 14:35 UTC, chris2733 requested changes

2022-11-28 14:35 UTC, chris2733 commented on src/components/Cohorts/StudentList/StudentsList.js
> +      <p>
fullInfo and simpleInfo could potentially be one component with the start/end date conditional, but this is more of a suggestion

2022-11-28 14:35 UTC, chris2733 commented on src/components/Cohorts/StudentList/StudentsList.js
> +      {asStudent === true ? <h1>My cohort</h1> : <h1>Students</h1>}
You could have this conditional inside of the h1 tag, this saves you having to type that tag twice

2022-11-29 12:45 UTC, lucianosimoni approved these changes

2022-11-29 12:45 UTC, lucianosimoni commented on src/components/Cohorts/StudentList/StudentListItem.js
> +    <div className="student-list-item">
Suggestion: This `<div>` could be the `<li>` itself, and it would be a direct child of `<ul>`

2022-11-29 15:47 UTC, OlhaDorofiychuk commented on src/components/Cohorts/StudentList/StudentsList.js
> +  const [students, setStudents] = useState([])
this state is used, we have updated code

2022-11-29 15:48 UTC, OlhaDorofiychuk commented on src/components/Cohorts/StudentList/StudentsList.js
> +      setStudents(studentsOnly)
please advise how would you refactor and what kind of bugs could current approach introduce?

2022-11-29 15:48 UTC, OlhaDorofiychuk commented on src/components/Cohorts/StudentList/StudentsList.js
> +        <u>{cohort.startDate}</u> -<u>{cohort.endDate}</u>
changed to div as per recomendation

2022-11-29 15:49 UTC, OlhaDorofiychuk commented on src/components/Cohorts/StudentList/StudentsList.js
> +      {renderInfo === false
sorted

2022-11-29 15:53 UTC, OlhaDorofiychuk commented on src/components/Cohorts/StudentList/StudentsList.js
> +      <p>
thank you, it is a valid point

2022-11-29 16:09 UTC, chris2733 approved these changes

2022-11-29 16:23 UTC, Auenc approved these changes

2022-11-29 16:23 UTC, merged