180 write an initials utilities component
boolean-uk/team-dev-frontend-client pull request #229
Opened 2022-12-03 12:38 UTC by akibria12

2022-12-03 16:22 UTC, lucianosimoni requested changes

2022-12-03 16:22 UTC, lucianosimoni commented on src/components/cohortsList/cohortListItem/CohortListItem.js
> +  console.log(cohort)
Can you just remove this console log? the rest is fine 🙂

2022-12-03 18:40 UTC, lucianosimoni approved these changes
nice!!!

2022-12-05 11:18 UTC, dogezen approved these changes

2022-12-05 11:18 UTC, merged